# version: '3.8'

services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel-net
    depends_on:
      - mysql
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  caddy:
    image: caddy:2-alpine
    container_name: laravel-caddy
    restart: unless-stopped
    ports:
      - "8003:80"
    volumes:
      - ./:/var/www
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app
    networks:
      - laravel-net
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_USER: ${DB_USERNAME:-laravel}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - laravel-net
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  redis:
    image: redis:alpine
    container_name: laravel-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - laravel-net
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

networks:
  laravel-net:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
  caddy_data:
  caddy_config: